---
version: "2.1"
services:
  prusaslicer-novnc:
    image: mikeah/prusaslicer-novnc
    container_name: prusaslicer-novnc
    environment:
      - SSL_CERT_FILE=/etc/ssl/certs/ca-certificates.crt
      - NVIDIA_VISIBLE_DEVICES=0
      - NVIDIA_DRIVER_CAPABILITIES=all
      - DISPLAY=:1
      - VGL_DISPLAY=egl # needed to run without X server
      - SUPD_LOGLEVEL=INFO 
      - VNC_RESOLUTION=1920x1080
    volumes:
      - ./prints:/prints/
      - ./data:/configs/
    restart: unless-stopped
